### ISSUE TITLE
Implement Tool 13_e

### ISSUE THREAD

**Issue by rabbl** [inowas/inowas-dss-client#12]
Implement Tool 13_e

**Comment by ramandeepjain** [comment]
Ok. I'll do it!

**Comment by rabbl** [comment]
![pasted image at 2017_02_18 07_50 pm](https://cloud.githubusercontent.com/assets/1965304/23117552/8538cc54-f750-11e6-87c3-c83d9b9a6134.png)

**Comment by ramandeepjain** [comment]
The variable 'ne', effective porosity is not used in the equation at all. Is there a mistake with the equation or the effective porosity should not be included in the variable list?

**Comment by ramandeepjain** [comment]
The equation number 4 is wrong. The example does not give the result as mentioned there.

**Comment by Catalinuss** [comment]
The graph plotted in the mockup from Ralf is just for design purposes, I don't know how it looks in reality. For questions to T13 a-e please contact Jana at jana.sallwey@tu-dresden.de (I'll send her the invitation to join discussions here).
