### ISSUE TITLE
Implement T16_a

### ISSUE THREAD

**Issue by Catalinuss** [inowas/inowas-dss-client#18]
The wiki link here: http://wiki.inowas.hydro.tu-dresden.de/t16-saturated-soil-hydraulic-conductivity/ (not so much helpful).

@Thomas: please arrange a meeting to explain Ramandeep how the tool should work. I'll post here the mockups and the Excel files from Miguel.

**Comment by Catalinuss** [comment]
![t16_a pop-ups](https://cloud.githubusercontent.com/assets/24956421/23404700/9243dc56-fdb6-11e6-917e-bf9ce1caf0ae.jpg)
![t16_a](https://cloud.githubusercontent.com/assets/24956421/23404701/925cf1f0-fdb6-11e6-9e25-18e9e56a6fcb.jpg)

**Comment by Catalinuss** [comment]
[sieve analisys wiki - Copy.xlsx](https://github.com/inowas/ModFlowTool/files/806698/sieve.analisys.wiki.-.Copy.xlsx)

**Comment by ramandeepjain** [comment]
Only one equation of 16a from wiki has been implemented.

**Comment by ramandeepjain** [comment]
Took the picture from 16b. It can be easily replaced afterwards. Should the user decide which equation one wants to use for the calculations?

**Comment by Catalinuss** [comment]
There is a decision tree in the Excel file for each standard, i.e. “IF 1 < U < 20 AND 0.06 < d10 < 0.6 THEN calculate K with Beyer” etc. In the mockup you see a dropdown list close to the K value. In that list only the methods are displayed that are validated by those IF conditions. In this case, yes, the user should have the possibility to select between these valid equations.

---
Dr. Catalin Stefan
Technische Universität Dresden
Faculty of Environmental Sciences
Institute of Waste Management and Circular Economy
Pratzschwitzer Str. 15
01796 Pirna
GERMANY

Tel.: +49-3501-530044
Fax: +49-3501-530022
Email: catalin.stefan@tu-dresden.de
http://www.tu-dresden.de/fghhiaa

Junior Research Group INOWAS
http://www.tu-dresden.de/uw/inowas

Journal of Vietnamese Environment
http://dx.doi.org/10.13141/jve

**Comment by Catalinuss** [comment]
<img width="1920" alt="screen shot 2017-03-02 at 06 55 38" src="https://cloud.githubusercontent.com/assets/24956421/23494821/4e53e1c0-ff15-11e6-8428-bbcc42832b6e.png">

**Comment by Catalinuss** [comment]
Hi,

I saw the implementation, it looks good but it's not only about implementing the equations. I asked Thomas to explain Ramandeep how the tool works and the Excel file has all the necessary steps. See also the mockups about how the final layout shall look like (the wiki page is incomplete!).

@Thomas: I asked you to explain please Ramandeep the tool, please get in touch with him ASAP.

Thanks
Catalin

---
Dr. Catalin Stefan
Technische Universität Dresden
Faculty of Environmental Sciences
Institute of Waste Management and Circular Economy
Pratzschwitzer Str. 15
01796 Pirna
GERMANY

Tel.: +49-3501-530044
Fax: +49-3501-530022
Email: catalin.stefan@tu-dresden.de
http://www.tu-dresden.de/fghhiaa

Junior Research Group INOWAS
http://www.tu-dresden.de/uw/inowas

Journal of Vietnamese Environment
http://dx.doi.org/10.13141/jve
